### ISSUE TITLE
Unable to alter path variable

### ISSUE THREAD

**Issue by urbantrout** [mocdk/MOC.NotFound#13]
In my site package's Configuration/Settings.yaml I added the following lines:

```
Neos:
  Flow:
    error:
      exceptionHandler:
        renderingGroups:
          notFoundExceptions:
            options:
              variables:
                path: '404'
```

But I get the error: `Uri with path "http://docker.vm/de/404.html" could not be found.`

Seems like the setting cannot be overwritten:

![bildschirmfoto 2017-10-13 um 15 49 52](https://user-images.githubusercontent.com/10465787/31549367-3dd135b2-b02e-11e7-918c-5a3d0507c88f.png)

**Comment by aertmann** [comment]
It's likely due to package loading order and the MOC.NotFound package being loaded after your site package. Make sure your site package depends on the MOC.NotFound package.. see my answer https://discuss.neos.io/t/proper-repository-structure/2699/8 for more details

**Comment by aertmann** [comment]
Added a note to the README for others 664f38dadfe0a3a9f894fc98f685c838e6c8db2b
