### ISSUE TITLE
Double //

### ISSUE THREAD

**Issue by OwlAsh** [mocdk/MOC.NotFound#4]
Fatal error: Uncaught exception 'Exception' with message 'Uri with path "http://www.xxx.de//404" could not be found.' in /home/030306-01_xxx.de/Neos-2.0/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/MOC_NotFound_ViewHelpers_RequestViewHelper.php:65 Stack trace: #0 [internal function]: MOC\NotFound\ViewHelpers\RequestViewHelper_Original->render('404') #1 /home/030306-01_xxx.de/Neos-2.0/Packages/Framework/TYPO3.Fluid/Classes/TYPO3/Fluid/Core/ViewHelper/AbstractViewHelper.php(302): call_user_func_array(Array, Array) #2 /home/030306-01_xxx.de/Neos-2.0/Packages/Framework/TYPO3.Fluid/Classes/TYPO3/Fluid/Core/ViewHelper/AbstractViewHelper.php(283): TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper->callRenderMethod() #3 /home/030306-01_xxx.de/Neos-2.0/Data/Temporary/Development/Cache/Code/Fluid_TemplateCache/Standalone_template_file_404_dbdf4a2c4b35c40c443173c497bafff09af1acf5.php(54): TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper->initializeArgumentsAndRender() #4 /home/030306-01_xxx.de/N in /home/030306-01_xxx.de/Neos-2.0/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/MOC_NotFound_ViewHelpers_RequestViewHelper.php on line 65

**Comment by OwlAsh** [comment]
The problem is that he make double slash.
The second problem is - maybe my fault - that he don't set a .html.
Is .html in the url not default? 
So its default 404.html and not 404.

**Comment by OwlAsh** [comment]
my fault, im sorry.
I forgot to set the default domain.

**Comment by mrimann** [comment]
I just ran into the exact same error.

@OwlAsh Could you explain how you solved the issue?

**Comment by OwlAsh** [comment]
@mrimann Please try to add the default domain.
Backend > Sites Manager > Edit ur created site > Add Domain

That should solve ur problem.

**Comment by mrimann** [comment]
Well, I did that (added "foobar.dev") already - yet the problem stays there and I see the following exception being logged:
`Uri with path "http://foobar.dev//404" could not be found.`

**Comment by OwlAsh** [comment]
@mrimann That was my error - so ...
May u clear the cache again? I dont trust them ... ;D

**Comment by mrimann** [comment]
Force-Flushed the cache but didn't help. Checked via GUI and CLI that the Domain is available and mapped to that Site - everything OK.

In the end, I could hardcode-hack it by modifying the View-Helper (line 62) as following:

Original:
`$httpRequest = Request::create(new Uri($parentHttpRequest->getBaseUri() . '/' . $path));`

Current (working):
`$httpRequest = Request::create(new Uri($parentHttpRequest->getBaseUri() . $path . '.html'));`

So what solved it for now was to remove the "/" that is added in between, and instead added a ".html" at the end. I'm not sure why this was needed at all...

@aertmann Maybe you know what could have gone wrong...?

**Comment by aertmann** [comment]
@mrimann good question.. I always remove the ".html" suffix in all my projects, so that might be the reason? Could you check if you do that it works?

**Comment by mrimann** [comment]
@aertmann yeah, I think this was the point: And it seems to be solvable in two ways:
- remove the `defaultUriSuffix` from the global route definition (then the package works out of the box)
- keep the `defaultUriSuffix` in the global config, but modify the config of your package to use `path: '404.html'` (with the .html-suffix)

I've now gone the first of those two paths. Thanks for the hint!
