### ISSUE TITLE
404 status code is returned twice

### ISSUE THREAD

**Issue by gerhard-boden** [mocdk/MOC.NotFound#6]
First of all thanks for the plugin, works great so far!

There is one little thing I noticed when monitoring the network traffic:
![image](https://cloud.githubusercontent.com/assets/10533739/14145035/82c4b98e-f692-11e5-9f8d-7ce141cff55e.png)

The status code 404 is returned twice. Once for the document, and another time for what seems to be the same document. Not a real issue, just curious if that is normal.

**Comment by aertmann** [comment]
@gerhard-boden it's not something I've experienced, just checked a couple of sites using the package.. it's likely related to an AJAX request from some Javascript on your page..

**Comment by gerhard-boden** [comment]
Sorry, you're right. Can't really tell where this is coming from at the moment,  but it's definitely site related.
