### ISSUE TITLE
exclude certain HTTP method from 404 status

### ISSUE THREAD

**Issue by gerhard-boden** [mocdk/MOC.NotFound#7]
I admit that this is a real edge case, but I'm asking anyway :smile: :

Is it somehow possible to exclude certain HTTP methods from the 404 status? 
The reason why I ask: There is a contactform embedded within my 404 page. When I hit send the POST request comes back with a 404 response.

**Comment by aertmann** [comment]
@gerhard-boden may I suggest you set a form action to a page that actually exists?

**Comment by gerhard-boden** [comment]
Thanks for the tip, that makes sense! 
Currently a form in Neos uses  the site it is on as `action`, that's the default behaviour. I'll look into it if I can change that somehow when i find the time!
